application:
  namespaceOverride: "apps"
  applicationName: "numbers-api"

  deployment:
    enabled: true
    reloadOnChange: false
    replicas: 2
    image: 
      repository: tairitzhak/numbers-api
      tag: 1.0.0
      pullPolicy: IfNotPresent
    containerSecurityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: false
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

    readinessProbe:
      enabled: true
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP

    livenessProbe:
      enabled: true
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP

    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #         - key: app.kubernetes.io/name
    #           operator: In
    #           values:
    #           - numbers-api
    #       topologyKey: "kubernetes.io/hostname"


  service:
    enabled: true   
    ports:
      - port: 8080
        name: http
        protocol: TCP
        targetPort: 8080
    type: ClusterIP