application:
  applicationName: "forwarder"

  deployment:
    enabled: true
    reloadOnChange: false
    replicas: 1
    image: 
      repository: 905418359591.dkr.ecr.us-east-1.amazonaws.com/forwarder
      tag: ""
      pullPolicy: IfNotPresent
    env:
      API_URL:
        value: "http://numbers-api.dev.svc.cluster.local:8080"
    containerSecurityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: false
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

    readinessProbe:
      enabled: true
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP

    livenessProbe:
      enabled: true
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP

  service:
    enabled: true   
    ports:
      - port: 8080
        name: http
        protocol: TCP
        targetPort: 8080
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: 'nginx'
    servicePort: http
    pathType: ImplementationSpecific
    hosts:
      - host: forwarder.public
        paths: 
        - path: /

