application:
  namespaceOverride: "apps"
  applicationName: "microservices"

  deployment:
    enabled: true
    reloadOnChange: false
    replicas: 1
    image: 
      repository: tairitzhak/microservices
      tag: 1.0.0
      pullPolicy: IfNotPresent
    env:
      API_URL:
        value: "http://numbers-api.apps.svc.cluster.local:8080"
    containerSecurityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: false
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

    readinessProbe:
      enabled: true
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP

    livenessProbe:
      enabled: true
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP

    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #         - key: app.kubernetes.io/name
    #           operator: In
    #           values:
    #           - microservices
    #       topologyKey: "kubernetes.io/hostname"

  service:
    enabled: true   
    ports:
      - port: 8080
        name: http
        protocol: TCP
        targetPort: 8080
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: 'nginx'
    servicePort: http
    pathType: ImplementationSpecific
    hosts:
      - host: microservices.local
        paths: 
        - path: /
